### ISSUE TITLE
For web-maa branch. On POST "body" is not part of the Type3 request options

### ISSUE THREAD

**Issue by coopernyc** [maa105/node-http-ntlm#2]
when httpReqExtraOptions assigned, you are omitting "body",
and type3options are missing body in post request

// build type3 request:
    var type3options = {
      url: url,
      method: method,
      headers: {
        'Connection': 'Close',
        'Authorization': type3msg
      }
    };

    // pass along other options:
    type3options.headers = Object.assign({}, headers, type3options.headers);

   **ADD BODY BACK, otherwise "body" is not sent to the server.** 
   type3options.body = body;

    type3options = Object.assign(type3options, httpReqExtraOptions);

**Comment by maa105** [comment]
just saw this issue. it is fixed. my apologies
